services:
  - type: web
    name: fluentfox-ui
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false # Set manually in Render dashboard
    healthCheckPath: /